### ISSUE TITLE
Repacking the boot.img won't boot on my device

### ISSUE THREAD

**Issue by winstonma** [draekko/AIK-Linux#1]
I used AIK Linux and just did the following

1. Unpack boot.img

1. Repack the content without modifying anything

1. Load the new boot.img to the device

I also unpack the new boot.img and compare the content with the original boot.img. It seems to me that the boot.img-ramdisk.cpio.gz has a different md5 value.

Here is the original [Boot.img](https://github.com/topjohnwu/Magisk/files/3775731/boot.img.zip).

Thanks for the help.

**Comment by draekko** [comment]
This is just my personal local repo version, i didn't create it and don't maintain it. I just update it from the forum thread on xda. Look a the read me where i get it from. Also i just updated it to v3.7 maybe that will help you.
